### ISSUE TITLE
No module named 'dvadmin3_celery'

### ISSUE THREAD

**Issue by ysun** [huge-dream/django-vue3-admin#22]
python3 manage.py makemigrations

```
(.venv) root@chuncheng:/home/works/django-vue3-admin/backend# python3 manage.py makemigrations                                                          
Traceback (most recent call last):                                                                                                                      
  File "/home/works/django-vue3-admin/backend/.venv/lib/python3.11/site-packages/django/core/checks/security/csrf.py", line 51, in check_csrf_failure_vi
ew                                                                                                                                                      
    view = _get_failure_view()                                                                                                                          
           ^^^^^^^^^^^^^^^^^^^                                                                                                                          
  File "/home/works/django-vue3-admin/backend/.venv/lib/python3.11/site-packages/django/middleware/csrf.py", line 51, in _get_failure_view              
    return get_callable(settings.CSRF_FAILURE_VIEW)                                                                                                     
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                      
  File "/home/works/django-vue3-admin/backend/.venv/lib/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__                     
    self._setup(name)                                                                                                                                   
  File "/home/works/django-vue3-admin/backend/.venv/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup                           
    self._wrapped = Settings(settings_module)                                                                                                           
                    ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                           
  File "/home/works/django-vue3-admin/backend/.venv/lib/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__                        
    mod = importlib.import_module(self.SETTINGS_MODULE)                                                                                                 
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                 
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module                                                                          
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                         
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                         
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import                                                                                       
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load                                                                                    
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked                                                                           
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed                                                                          
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import                                                                                       
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load                                                                                    
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked                                                                           
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked                                                                                     
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module                                                                               
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed                                                                          
  File "/home/works/django-vue3-admin/backend/application/__init__.py", line 3, in <module>                                                             
    from .celery import app as celery_app                                                                                                               
  File "/home/works/django-vue3-admin/backend/application/celery.py", line 10, in <module>                                                              
    if "django_tenants" in settings.INSTALLED_APPS:                                                                                                     
                           ^^^^^^^^^^^^^^^^^^^^^^^                                                                                                      
  File "/home/works/django-vue3-admin/backend/.venv/lib/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__                     
    self._setup(name)                                                                                                                                   
  File "/home/works/django-vue3-admin/backend/.venv/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup                           
    self._wrapped = Settings(settings_module)                                                                                                           
                    ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                           
  File "/home/works/django-vue3-admin/backend/.venv/lib/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__                        
    mod = importlib.import_module(self.SETTINGS_MODULE)                                                                                                 
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                 
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module                                                                          
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                         
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                         
  File "/home/works/django-vue3-admin/backend/application/settings.py", line 407, in <module>                                                           
    from dvadmin3_celery.settings import *            # celery 异步任务                                                                                 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                              
ModuleNotFoundError: No module named 'dvadmin3_celery'                                                                                                  
```

**Comment by ysun** [comment]
Add the solution in the README.md in this PR:
https://github.com/huge-dream/django-vue3-admin/pull/23
