### ISSUE TITLE
前端install一直失败，yarn install和npm install都失败了

### ISSUE THREAD

**Issue by jialinl525** [huge-dream/django-vue3-admin#6]
3181 verbose node v20.13.1
3182 verbose npm  v10.5.2

C:\001-Automation\django-vue3-admin\web> yarn install
➤ YN0000: · Yarn 4.2.2
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: e-icon-picker@workspace:./lib: Workspace not found (e-icon-picker@workspace:./lib)
    at St.getWorkspaceByDescriptor (C:\Users\jialinl\AppData\Local\node\corepack\v1\yarn\4.2.2\yarn.js:210:3520)
    at l1.getCandidates (C:\Users\jialinl\AppData\Local\node\corepack\v1\yarn\4.2.2\yarn.js:140:115276)
    at Pd.getCandidates (C:\Users\jialinl\AppData\Local\node\corepack\v1\yarn\4.2.2\yarn.js:141:1311)
    at Pd.getCandidates (C:\Users\jialinl\AppData\Local\node\corepack\v1\yarn\4.2.2\yarn.js:141:1311)
    at C:\Users\jialinl\AppData\Local\node\corepack\v1\yarn\4.2.2\yarn.js:210:8409
    at Ky (C:\Users\jialinl\AppData\Local\node\corepack\v1\yarn\4.2.2\yarn.js:140:53916)
    at Fe (C:\Users\jialinl\AppData\Local\node\corepack\v1\yarn\4.2.2\yarn.js:210:8389)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.allSettled (index 5)

[2024-05-13T09_46_34_343Z-debug-0.log](https://github.com/huge-dream/django-vue3-admin/files/15301740/2024-05-13T09_46_34_343Z-debug-0.log)

    at async _c (C:\Users\jialinl\AppData\Local\node\corepack\v1\yarn\4.2.2\yarn.js:140:53244)

**Comment by qn2060** [comment]
同样问题
![image](https://github.com/huge-dream/django-vue3-admin/assets/15309040/a9649648-178e-4f5d-9824-5c36919843ea)

**Comment by Elm1992** [comment]
@qn2060 我刚刚也遇到这个问题了，直接用e-icon-picker2.1.1就好了，他这个高版本应该是有问题，项目里引入这种star少的库风险确实太高。

**Comment by jialinl525** [comment]
已解决。
解决方式：将e-icon-picker先从package.json中移除，再单独安装e-icon-picker 2.1.1就好
